# Generated by Django 5.2.7 on 2025-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productscreenshot_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_text',
            field=models.CharField(default='Click Here', help_text='Text for the action button', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='external_link',
            field=models.URLField(blank=True, help_text="Link for 'Buy/Click' button", null=True),
        ),
    ]
